### ISSUE TITLE
Readline tab completion

### ISSUE THREAD

**Issue by rirel** [kimtg/arcadia#10]
Readline's default autocomplete behavior uses the contents of the current directory, which isn't very useful when using Arcadia's REPL mode. Eventually custom autocomplete based on the global environment would be neat, but for now it probably makes the most sense to disable the default autocomplete behavior by unbinding the tab key.

```
rl_bind_key('\t', rl_insert); /* something like this should do it */
```

Also, perhaps providing access to this functionality from Arcadia's readline API would be a good idea. This way arc programs would be able to specify a custom autocompletion procedure when they call `(readline)`.

**Comment by kimtg** [comment]
Thank you. Tab completion disabled now.
