### ISSUE TITLE
rev function

### ISSUE THREAD

**Issue by Kerrigan29a** [kimtg/arcadia#12]
First of all, thanks for your implementation. I'm using it to learn functional programming without having to install a huge implementation of Common LISP or Scheme.

I'm having a problem with `rev`. If I call it for the first time I get an error, but if I copy the original code from the library and I call it again, it works

```
./arcadia
Arcadia 0.11.2
> (rev '(1 2 3))
Symbol not bound : recur
>
> (def rev (xs)
  "Returns a list containing the elements of 'xs' back to front."
    ((rfn recur (xs acc)
      (if (no xs)
        acc
        (recur cdr.xs
               (cons car.xs acc)))) xs nil))
(fn (xs) "Returns a list containing the elements of 'xs' back to front." (((fn (recur) (assign recur (fn (xs acc) (if (no xs) acc (recur (cdr xs) (cons (car xs) acc)))))) nil) xs nil))
>
> (rev '(1 2 3))
(3 2 1)
>
```

**Comment by kimtg** [comment]
The problem has been fixed. It was caused by wrong ordering in the library file.

**Comment by Kerrigan29a** [comment]
Thank you
