### ISSUE TITLE
nil should be ignored in string arguments

### ISSUE THREAD

**Issue by 4d47** [kimtg/arcadia#15]
From [Arc tutorial](http://www.arclanguage.org/tut.txt)

    Every argument will appear as it would look if printed out by pr,
    except nil, which is ignored.

Arcadia 0.12

    > (string "hello" nil)
    "hellonil"

**Comment by kimtg** [comment]
Thank you. The problem has been fixed.
```
Arcadia 0.12.1
> (string "hello" nil)
"hello"
```
