### ISSUE TITLE
Arcadia segfaults when you invoke (type) with no arguments

### ISSUE THREAD

**Issue by rirel** [kimtg/arcadia#8]
Of course, there's no real reason to do this, so the issue doesn't (visibly, at least) hinder usability. Nonetheless it's probably worth looking into, since whatever's causing the segfault could potentially impact other functionality.

```
Arcadia 0.9.23
> (type)
[1]    51236 segmentation fault  ./arcadia
```

Update:
The problem appears to be stemming from line 1196 of arc.c. I don't want to jump to conclusions, but it's probably one of those assuming-something-exists-when-it-doesn't issues. Should be an easy fix, but I'm short on time at the moment. I'll look into it further later today.

**Comment by kimtg** [comment]
Thank you. Problem fixed now.
